[theme]
primaryColor="#BB86FC"
backgroundColor="#121212"
secondaryBackgroundColor="#1E1E1E"
textColor="#E0E0E0"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"